# Generated by Django 5.0.6 on 2024-10-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_newsarticle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsarticle',
            table='myapp_newsarticle',
        ),
    ]
